# Autogenerated wrapper script for CoreMath_jll for aarch64-apple-darwin
export libcoremath

JLLWrappers.@generate_wrapper_header("CoreMath")
JLLWrappers.@declare_library_product(libcoremath, "@rpath/libcoremath.dylib")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libcoremath,
        "lib/libcoremath.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
